name: micit_test
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  dio: ^5.4.2+1
  fade_shimmer: ^2.2.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  google_sign_in: ^6.2.1
  infinite_scroll_pagination: ^4.0.0
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.8.1
  logger: ^2.2.0
  sqflite: ^2.4.0

dev_dependencies:
  analyzer: ^6.4.1
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter_intl:
  enabled: true
  arb_dir: lib/src/core/config/l10n
  output_dir: lib/src/core/config/l10n/generated

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_gen:
  output: lib/src/core/config/assets/ # Optional (default: lib/gen/)
  line_length: 120 # Optional (default: 80)
