// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPbq4j6RVSJY6lOdQSFpWcJMFwxdiOxAw',
    appId: '1:476653837304:android:64f84e34a76dae1163d40d',
    messagingSenderId: '476653837304',
    projectId: 'micit-task',
    storageBucket: 'micit-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVFC8tJwom9GLEaT-1NvuaUmTovj9eW6E',
    appId: '1:476653837304:ios:1210c4b00e9575d563d40d',
    messagingSenderId: '476653837304',
    projectId: 'micit-task',
    storageBucket: 'micit-task.appspot.com',
    androidClientId: '476653837304-dpvubod8503hb1suih7mlo7cdfm8ub9c.apps.googleusercontent.com',
    iosClientId: '476653837304-kkcn9deb6a53382nf382m1o7l670cvkh.apps.googleusercontent.com',
    iosBundleId: 'com.example.micittest',
  );
}
